"""MPL Season 2 auction state definitions."""

WAITING_FOR_GROUP = "WAITING_FOR_GROUP"
LIVE_BIDDING = "LIVE_BIDDING"
LOT_SOLD = "LOT_SOLD"
PAUSED = "PAUSED"
ROUND_2 = "ROUND_2"
COMPLETED = "COMPLETED"

VALID_STATES = {
    WAITING_FOR_GROUP,
    LIVE_BIDDING,
    LOT_SOLD,
    PAUSED,
    ROUND_2,
    COMPLETED,
}
